### ISSUE TITLE
Add Blog Home & Posts

### ISSUE THREAD

**Issue by bndnio** [bndnio/simbs#1]
Add blogging to the new website. This would require both a blog home and blog pages.

### Requirements:
**Blog posts should have:**
- Titles
- Authors
- Author dates
- Sharing links
- Feature image
- Images with captions
- Quotes
- Sections of text

**The Blog home should:**
- List the blog posts in order of newest first
- Show blog titles
- Show blog authors & dates
- Preview the feature image
- Give the ability to load more blog posts
- Show available post labels, and allow filtering on them

**Comment by bndnio** [comment]
### Mocks:
#### Blog page:
![new doc 2020-07-07 18 50 55_2 2](https://user-images.githubusercontent.com/11308382/86865921-d3367900-c084-11ea-8737-0ee1942adbdc.jpg)
#### Blog home:
![new doc 2020-07-07 18 50 55_1 2](https://user-images.githubusercontent.com/11308382/86865923-d3cf0f80-c084-11ea-937b-3e80aaa244c6.jpg)

**Comment by bndnio** [comment]
Another thing to consider is adding asset downloads and links to blog posts. The use case being a press release, it's good to have as a "blog post", but if someone would like to print it off or share it via pdf, we should include a downloadable link to the file

**Comment by SIMBS-HJ** [comment]
Looks great. Will this only accommodate images or can video be added?

**Comment by SIMBS-HJ** [comment]
I know this will link to Facebook, is there anyway that userS can react or respond to blogs on the website or is this a one way channel of communication?

**Comment by bndnio** [comment]
> Looks great. Will this only accommodate images or can video be added?

Good point!  
I would think that the banner would remain restricted to images, but within the post I think we should allow embedded videos.

> I know this will link to Facebook, is there anyway that userS can react or respond to blogs on the website or is this a one way channel of communication?

I was initially imagining this being one-way, but with the use of Facebook or Instagram login I can look into the feasibility of adding comments. I'll make a ticket for that!

**Comment by SIMBS-HJ** [comment]
I’m not sure yet whether we would want it two way, might be a lot more to manage

**Comment by bndnio** [comment]
Feature Complete:
![Screen Shot 2020-08-03 at 12 05 04 PM](https://user-images.githubusercontent.com/11308382/89217771-937a8880-d581-11ea-907a-2a006a7120f2.png)
---
![Screen Shot 2020-08-03 at 12 05 35 PM](https://user-images.githubusercontent.com/11308382/89217803-a55c2b80-d581-11ea-886e-ee9c8e140181.png)
