### ISSUE TITLE
Add Events Page

### ISSUE THREAD

**Issue by bndnio** [bndnio/simbs#10]
Events gives SIMBS a way to communicate opportunities for the community to engage. That could be an AGM, trail maintenance day, group ride, or deadline for a call to action (i.e. submitting letters to the CRD).

This page should:
- contain a calendar to give users a summary of what's happening
- prompt users to add the SIMBS calendar to theirs so they can see updates on their phone, laptop, etc.
- potentially link to facebook or another platform where there is a feed of events, or more event information
- give members the ability to easily suggest ideas for events (with the hopes that we could even to volunteer to run it)

**Comment by SIMBS-HJ** [comment]
Potentially link to Eventbrite to purchase tickets.

**Comment by bndnio** [comment]
Complete
