### ISSUE TITLE
Add Membership Page

### ISSUE THREAD

**Issue by bndnio** [bndnio/simbs#3]
Going forward, membership will be managed by a 3rd party platform (likely TidyHQ, or JoinIt), so a membership page doesn't require a tonne of functionality.

That being said, it should at least:
- Describe what members get out of a membership (i.e. why they should buy)
- Where their money goes
- Link to the membership platform (or somehow inline some page from the membership platform)

**Comment by SIMBS-HJ** [comment]
We talked about potentially having a waiver to sign but maybe that could be on the event page that people can complete online prior to showing up at an event

**Comment by bndnio** [comment]
Development is complete. Still needs content.

@SIMBS-HJ Good idea about the waiver on the events page. Let's discuss when meeting up what that looks like. It's super easy to drop in place when we have it.

**Comment by bndnio** [comment]
Complete
