### ISSUE TITLE
Add Trails Page

### ISSUE THREAD

**Issue by bndnio** [bndnio/simbs#7]
Trails will be one of the most involved aspects of the site, and hopefully one of the most used. As a result, prior to coming up with requirements we should first explore use-cases for people using this page.

Uses cases for a page dedicated exclusively to trails are:
- As a new mountain biker, where can I find specific trails or routes that I will have fun and comfortable on?
- As an experienced mountain biker, what trails are new or have new features that I can go ride?
- As a person new to the city and comfortable biking, what parks are around that I can mountain bike at?
- As a person just visiting to the city, given my skill level where should I travel and what trails should I ride?

Trail-building related use-cases are:
- As a part-time trail-builder, what trails exist that could use trimming, raking, etc.?
- As someone who would like to learn how to trail-build, or contribute in a group format, when are the next trail-building days?
- As someone on the fence about trail-building when is SIMBS going to work on the trails I love (and when should I come to trail maintenance days)?

**Comment by SIMBS-HJ** [comment]
Yeah, we were also talking about having trail forks connected.

**Comment by SIMBS-HJ** [comment]
Also maybe some recommended loops

**Comment by SIMBS-HJ** [comment]
Any notices about trails

**Comment by bndnio** [comment]
Complete
